<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFOuZ7Ez\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFOuZ7Ez/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFOuZ7Ez.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFOuZ7Ez\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFOuZ7Ez\App_KernelDevDebugContainer([
    'container.build_hash' => 'FOuZ7Ez',
    'container.build_id' => '16b5f729',
    'container.build_time' => 1643713183,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFOuZ7Ez');
